"""Prometheus metric definitions for Wukong-serve.

Importing this module is sufficient to register every metric. Code that needs
to observe values just imports the named metric and calls the standard
prometheus_client API on it.
"""

from prometheus_client import Counter, Gauge, Histogram

# Counter of every inference request that completes, by model / status / tier.
# status is one of: success | error | timeout | circuit_open | rate_limited
inference_requests_total = Counter(
    "inference_requests_total",
    "Total inference requests processed.",
    labelnames=("model", "status", "tier"),
)

# End-to-end latency for inference requests (seconds). Buckets chosen for an
# interactive LLM workload — anything past 10s is essentially a timeout.
inference_latency_seconds = Histogram(
    "inference_latency_seconds",
    "Inference latency in seconds, measured wall-clock end-to-end.",
    labelnames=("model",),
    buckets=(0.5, 1.0, 2.0, 5.0, 10.0),
)

# Tokens generated, summed across the lifetime of the process.
inference_tokens_generated_total = Counter(
    "inference_tokens_generated_total",
    "Total tokens generated by the model.",
    labelnames=("model",),
)

# Gauge of in-flight inference requests. Useful for autoscaling signals.
active_inference_requests = Gauge(
    "active_inference_requests",
    "Inference requests currently being processed.",
)

# Requests that were rejected by the rate limiter, by tier.
rate_limit_rejections_total = Counter(
    "rate_limit_rejections_total",
    "Requests rejected by the rate limiter.",
    labelnames=("tier",),
)

# Circuit breaker state: 0 = closed (healthy), 1 = open (failing fast).
circuit_breaker_state = Gauge(
    "circuit_breaker_state",
    "Circuit breaker state for the Ollama backend (0=closed, 1=open).",
)
